module.exports = {
  apps: [
    {
      name: 'orda-server',
      cwd: './server',
      script: 'index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 100,
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        SUPABASE_URL: 'https://zscxzwzjcatxvdflgavz.supabase.co',
        SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzY3h6d3pqY2F0eHZkZmxnYXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMjE1ODIsImV4cCI6MjA5NDU5NzU4Mn0.Lh3J1IxgqXHjTEt8FOXBhDgOehK1xNxP4o_hq-pR6Bw',
        GEMINI_API_KEY: 'AQ.Ab8RN6LYCId5SgLdQwbwSpkjmP2pp-mDk681nyd_ojCt7sg_6A',
      },
      error_file: '../logs/server-error.log',
      out_file: '../logs/server-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'orda-next',
      cwd: './',
      script: 'node_modules/.bin/next',
      args: 'start',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        EXPRESS_URL: 'http://localhost:3001',
        NEXT_PUBLIC_SUPABASE_URL: 'https://zscxzwzjcatxvdflgavz.supabase.co',
        NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzY3h6d3pqY2F0eHZkZmxnYXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMjE1ODIsImV4cCI6MjA5NDU5NzU4Mn0.Lh3J1IxgqXHjTEt8FOXBhDgOehK1xNxP4o_hq-pR6Bw',
      },
      error_file: './logs/next-error.log',
      out_file: './logs/next-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
